title: ITEG
email:
description: >-
    Additional Material
baseurl: "/tma2024-iteg" # the subpath of your site, e.g. /blog

github_ssh: git@github.com:tma2024-iteg/tma2024-iteg.git
github_link: https://github.com/tma2024-iteg/tma2024-iteg

github_username:

theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme


syntax_highlighter_style: github

collections:
  pages:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
